name: Publish package to GPR

on:
  release:
    types: [created]

jobs:
  build-test-publish:
    name: Build, test and publish package to GPR
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: 'yarn'
          registry-url: 'https://npm.pkg.github.com/' # Use GPR
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Build
        run: yarn build
      - name: Publish
        run: yarn publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Use GITHUB_TOKEN for GPR
